package com.paydue.dto;
// Generated Jul 27, 2015 3:59:23 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "sakila")
public class LoginForm implements java.io.Serializable {

	
	
	private int id;
	@NotEmpty	
	private String userName;
	@NotEmpty
	@Size(min = 1, max = 10)
	private String password;

	public LoginForm() {
	}

	public LoginForm(int id, String userName, String password) {
		this.id = id;
		this.userName = userName;
		this.password = password;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
